### PR TITLE
Vue post component (;

### PR DESCRIPTION
**Pull request by pufferfish101007**
Self explanatory.
There are loooooads of conflicts, I'll try and sort them out on my end but it might not be possible. I think it all works, but I need to sort out the fact that at the moment the love button and count is in the top left rather than bottom right. I'll unmark it as a draft when that's done, but I really can't see what I've managed to change to have it like that.

### CODE REVIEW

**Comment by pufferfish101007** [comment]
This pr's being glitchy. I'm going to make a new one.

**Comment by jeffalo** [comment]
@pufferfish101007 it might just be best to look at the changes, and then reimplement them to avoid conflicts and weird github issues, i can do it if you want

**Comment by pufferfish101007** [comment]
@jeffalo yes what I'll do is delete my fork (I've been meaning to do that anyway), create a new one, apply the changes, test it again, push again and then pr.

**Comment by kozz168** [comment]
{"webId":"jd2goi"}

**Comment by pufferfish101007** [comment]
> {"webId":"jd2goi"}

?????

**Comment by kozz168** [comment]
Request Id: 03c013c5-615e-4068-928a-d697cf798800
Correlation Id: d6239bd4-0831-40cc-b844-9320a2619832
Timestamp: 2020-12-31T00:15:44Z
Message: AADSTS50020: User account 'viv718918@gmail.com' from identity provider 'live.com' does not exist in tenant 'Microsoft Services' and cannot access the application 'cb5b7de5-2ef8-4fb2-9600-9feadb91dc45'(Microsoft Launcher) in that tenant. The account needs to be added as an external user in the tenant first. Sign out and sign in again with a different Azure Active Directory user account.

**Comment by YOYITsM3M8** [comment]
> Request Id: 03c013c5-615e-4068-928a-d697cf798800
> Correlation Id: d6239bd4-0831-40cc-b844-9320a2619832
> Timestamp: 2020-12-31T00:15:44Z
> Message: AADSTS50020: User account '[viv718918@gmail.com](mailto:viv718918@gmail.com)' from identity provider 'live.com' does not exist in tenant 'Microsoft Services' and cannot access the application 'cb5b7de5-2ef8-4fb2-9600-9feadb91dc45'(Microsoft Launcher) in that tenant. The account needs to be added as an external user in the tenant first. Sign out and sign in again with a different Azure Active Directory user account.

?

**Review by habib500 — COMMENTED** [review]
Pull requests

**Pull request closed without merging**
