### PR TITLE
Rate limiting and code cleanup

### LINKED ISSUE #4: clean up
clean up code,

make functions for common things, avoid callback hell, sensible variable names etc.

this also includes database, so this should be done before release so that having to wipe database isn't a big deal

something else that would be nice would be to use express middlewares to consistently know if the user is logged in, and if so their data from the database
i think that would be a middlware at the start that sets res.locals to the user from the database
https://stackoverflow.com/questions/18875292/passing-variables-to-the-next-middleware-using-next-in-express-js

if someone could help with this it would be really nice :)

### LINKED ISSUE #33: do not say if password is incorrect or if user doesn't exist
standard saftey practice

### LINKED ISSUE #34: rate limit

### PR DESCRIPTION
**Pull request by pufferfish101007**
Resolves #33 
Resolves #34
Partially resolves #4 

Ok, so there are a lot of changes here:

- I added rate limiting, 5/hr for creating accounts, and 100/hr for the api. These are subject to change.
- I cleaned up the code a bit so that repeated checks for whether a user is logged in or not are now handed in the middlewares `checkLoggedIn` and `checkLoggedOut`. (not to self: need to add default cb if cb isn't specified) They make the code slightly cleaner and easier to understand, but they do add lots of extra lines due to `code formatting`.
- <s>I added [defresh](https://github.com/derder56/defresh) to make sure pages don't reload when links are clicked, making it about 2x faster. Github, discord, discourse and twitter all use similar techniques.</s >
- don't say whether username or password is incorrect
- added `body-parser` to dependencies
- lines now consistently end in semicolons
- I also just realised that all quotes are now double quotes <s>I hate you so much prettier </s>
- There might be some other things I've forgotten
- 
It might look like I've changed every line in index.js, but don't worry - I left about 20 unchanged.

### CODE REVIEW

**Comment by jeffalo** [comment]
really neat, i can't wait to check this out. im not so sure about defresh though btw

**Comment by Zxnii** [comment]
jeffalo losing all copyright he had on his code go brrrr

**Comment by jeffalo** [comment]
alright so some things,
- no defresh (it does bad things)
- as mentioned in the discord, the formatter made the lines really short, idk about that though
- thank you so much for the pr!! 👍 
- happy holidays!

**Comment by pufferfish101007** [comment]
- defresh is gone
- I couldn't get the code to format nicely - you'll just have to live with that, sorry 

I also added fallback callback to the new logged in checks middleware so it's even more veautiful to gaze at this already beautiful code

**Comment by jeffalo** [comment]
litteraly awesome!!!

**Pull request merged**
