### PR TITLE
Tailwind 2.0

### PR DESCRIPTION
**Pull request by GrahamSH-LLK**

### CODE REVIEW

**Comment by jeffalo** [comment]
nice work!!! the post component content text used to be slightly grey

before
image

after
image


but otherwise near perfect migration!!! i dunno if you touched the sweet alert styles in head.ejs but maybe that should match the new indigo colour.

**Comment by GrahamSH-LLK** [comment]
> nice work!!! the post component content text used to be slightly grey
> 
> before
> image
> 
> after
> image
> 
> but otherwise near perfect migration!!! i dunno if you touched the sweet alert styles in head.ejs but maybe that should match the new indigo colour.
> 
> once those are done it should be safe to merge

I did a full repo search and replace, so we should be good!

**Comment by jeffalo** [comment]
@GrahamSH-LLK theres no new commits, did you push?

**Comment by GrahamSH-LLK** [comment]
I did that in my 1st commit.

**Comment by GrahamSH-LLK** [comment]
All problems fixed @jeffalo

**Pull request merged**
